name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  COMPOSE: docker compose -f docker/prod.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            git pull
            cd ..
            ${{ env.COMPOSE }} down
            ${{ env.COMPOSE }} up -d --build